language: objective-c
osx_image: xcode10

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install:
- bundle install

script:
- set -e
- pod install
- fastlane beta
- git clone https://github.com/apptestai/ci_addon
- export binary_path=HackerNews.ipa
- export project_id='825'
- bash ./ci_addon/step.sh

deploy:
  provider: releases
  api_key:
    secure: BZgq2xKTtZ0tfeHDsGfUtcN93E2nxLuHsgVIIm6bRhSH9JGsuHpDxdg/2NAmVMcEfqZfBZM72QNqDrxcXcJJGwjE9JPBnsjjZJb8KIp1WWr9bMUS3C2D5Shl0LWgaIYhj0InYUZwXjGft2MmmRA8bJlLTG7kDePvDxxRVKQjovYwdLny+YGE8M2tJWRisy25WDryuIuf3giSVVeYta/hw87hHNyjWqTyfuYDKDqK3/CkdB7I49t3Mo5cyYeg94Iy5z9G59Mo4w1LPNPFdb7bsVZs6KCujpoj5Jm1S+5zVW7eSsx9Zm55rCgjmnlvZ9J9k2iz3ZmEPshi6xGawj6boPrcaqFBjKNAdwCEHdsrvSlhT0PWXXeoE/OSWH+2H1dnjy/rx9q5TfFudNItjlqum85XtsD4hu2qodcbW3L/hyF68FpeNLp743o4wt0HTD56J49xwoHZjh/HcoykWYxv2WK8uWsLY+UiTt0evJigD7Z5pnRCgubNIaQeRZTOuB0kloXhDvX5GXV3/nbF4J7ySPCogNO481XrgTi0jzv3HQWEu/nu9PTOFg0ceJrAQECeyFQ8Xs7c4dzuWm73yPykDLGphHY6/HFNwbp0p20e7+3zkzvhPrs7kDQ2cnMXSbb3/fab1MNxfQDZiG1ELN9uQkVoEsf4SqWhA8Lu1cZpy/0=
  file: test-results/apptest-ai_result.html
  skip_cleanup: true
  on:
    repo: apptestai/HackerNews

env:
  global:
  - secure: fUnmuuqKmxWjxGHbfTB7QZgSmkB7yvt6KGAn8dCs1j4GneWbSIrEhghRrlOMQCThhMoetou4H+NaWeTXRRa4fpoCGm1U51RbD+J4DrbKWj3MzRupzByEAsaWhmvCaYVgCOlkYgaApcvujIrpw1rUTQVio8+WoYIXgXx3BZF06VN50oNT58BUZAD/UUeEacp8GEI5tcPbsbaKbPqy2Rb5HSQ+RkSfAWJhuA+x4RT8l8geXRdUhtrT00EasL7a7p/4OIPkW4pAGvBth/jiDoWA3N2tDME7AOU+whvt9tVju9Db/WKarWYCkPuSVwHTUH6W9o3TyvLLgAsapbgrS7DtJkJx5NoPNyZa5WrlnOdNAerSgQRC724sfSM4dHrYhkSWHRueAjD9X0JbS5TEUeTnw2XHbq+hbc/5aFR/CnZFkTSv6XItnL6ES6tz/nQjNZfIdsHRFfoTCre1Uah3zAu0veHh7d1srvq91lvc3VSrnuhSoNpegPSc1NZ5dmN1VkhLRt7q8hSU1HMpBYe76q58UyfS02BjTswQJOoQHmBDl+DDv045qi4q1/hfCd/JqGNgH3bp2KtZxV0uq+aUicC7XWhaHyaVaGnVJa94kqayxNsoFP3zOse//VlIL46iHDSpuIzXCcgR2IT59T+E5i/c1fOzA65KEn8Aw7cr/5R8W2s=
  - secure: yXlFmmgo3QIeH43qSeKTol7Fl/IWvKGLh3ycAdgTnFUfocPnHYhIV3b0ykvoLxSyDPeV/Rre8uhAXLAas3w/XFYWOvobE/qgEDbc+7dYKT5xWXqaW9MfYVnnVsuBgDZNPdHsZPyclF+q4H5Y2Le8b9VCkXIHxmspHrFXnTt7mRqCf9xPFBJCQKFfMTQs2sOBuILh2SpOP39seNyX52p4cPg2ZRpncghml86JScuwRSFrBlI2vDBvQLzT0SenDtsmnVQfGdVTw6Vp8IfapvNp9FXakPdSuwovNQAANhSAMyCwaTb08gXS04OSIPl+DwezZnDzhdpisL5RPYQEbjSGk70l536AaM1VOoAN4991fyW5aLf93vDqEnh5TmBQqrK/RD3KsUaCcXh/cwk3yRvB3Wt1LdTX+NV1FnE4kwDodF+zB6ueumFinG1Qkx4HV8RanDvRGKSxK89SlDXCbiZ/tl8vzIdPh5p4u4/+Lxt8iPgIA/0MovpQFDVnmEGpRoPclwSHBu2tt6LLH57+n7r3Wd1C0aMMzM+Nr582MrxGkxPGBIA84741Vy5g3hZ9aTF9VSz5+sHseelXZYQcGXDNNZbeFy3rtNgavQVETsXDu1c2kWNvkPxoPl9SNmxMn1mNIb5ROCCQjku5icAyZFE+3zwGLFnSWn0WaN5mqZs+Dqc=
  - secure: CzEyJF6epoEK9E8FmSO4QuxiKssdn0te84Mvaqrp2F4atueiZYntAryxEobEx8bZFu3tdCGlDPbgyoo7W4goRc/zij4P41C/LtAxqQWvz4KGCpADJsGYGYij+0DHbwZpgbN9sg1o32NjDRNx+uAxzp/iGyIkwC8wA4CVSXzKsfyQ2LMHDtZbKeDj+ZxOjRfzVD9461KgFpIYWZTmmHVS6n0/EfOP7WEVaZmehlOV8kpsO59E/YMD0U6STvmwa+4+9tyYT3mKJEH1GcxePbWz5oyxCmcvhrKhBmhIvbndA7lFcXW/4/sr6Mrf38/8wChQqRweiZyFk5M1lMAnKfOgwP2H9K8LbxKE+hv5MpC2FPq1h1z8BM8/OfFEZjgYClA5/YN7MMpyP2G25z9n8bYu8d3hkOASi23lQVMjIPwyCe9OCrQofpn7dI3WvvmT/+vYGxBqWFrLlHYRMRlYzFaesUwc00BBdxmirCk+BSwS5Lq0iOvEdyHM6A+QokHMHKAJxKZFZ9LvOF3G5sDB2b3oiuKszf7qqm3JRT4271tB2JWvyIc+jey/DU2VOaP79RFAizsw2sIsHiOULl1HHCrHamLLknnKpGYVesrfAjecAoW9eSubrq+qtSZXUUf+AtTquVqmgSl11G+ZFfCWrxVu5X9yb0VA0mUY/rFU/xoS/Co=
