version: 2.1
orbs:
  apptest-ai: apptestai/app-test@dev:0.0.1
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build and archive
          command: fastlane ios beta
      - apptest-ai/run-test:
          binary_path: ./HackerNews.ipa
          project_id: '794'          
      - store_artifacts:
          path: ./HackerNews.ipa
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
      
