default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :beta do
    match(type: "development" )
    build_ios_app(
      scheme: "HackerNews",
      export_options: {
        method: "development",
    	provisioningProfiles: { 
          "ai.apptest.*": "match Development ai.apptest.*",
          "ai.apptest.ai.hackernews": "match Development ai.apptest.*"
        },
        signingStyle: "manual"
      }
    )
  end 
end
